# Usar una imagen base de Node.js
FROM node:14-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install --production

# Copiar el resto de los archivos de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación Express va a escuchar
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "index.js"]
